[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["node_modules", "lib"]
script = "scripts"
solc_version = "0.8.28"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@symbioticfi/=node_modules/@symbioticfi/",
    "forge-std/=lib/forge-std/src/",
]

[profile.release]
gas_reports = ["*"]
gas_reports_ignore = ["MockERC20", "MockOracle"]
optimizer = true
optimizer_runs = 20000
via_ir = true


[rpc_endpoints]
mainnet = "${MAINNET_RPC}"

[etherscan]
mainnet = { key = "${MAINNET_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
