[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["node_modules", "lib"]
script = "scripts"
solc_version = "0.8.28"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/interfaces/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/contracts/interfaces',
    '@layerzerolabs/lz-evm-messagelib-v2=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    'solidity-bytes-utils/contracts/=lib/solidity-bytes-utils/contracts',
    '@symbioticfi/burners/=lib/symbioticfi-burners',
    '@symbioticfi/core/=lib/symbioticfi-core',
    '@symbioticfi/middleware-sdk/=lib/symbioticfi-middleware-sdk',
    '@symbioticfi/hooks/=lib/symbioticfi-hooks',
    '@symbioticfi/rewards/=lib/symbioticfi-rewards',
]
fs_permissions = [
    { access = "read", path = "./script/config/layerzero-v2-deployments.json" },
]

[fmt]
bracket_spacing = true
int_types = "preserve"
sort_imports = true
single_line_statement_blocks = "preserve"
contract_new_lines = false

[profile.release]
inherits = "default"
gas_reports = ["*"]
gas_reports_ignore = [
    "MockAaveDataProvider",
    "MockChainlinkPriceFeed",
    "MockDelegation",
    "MockERC20",
    "MockOFT",
]
optimizer = true
optimizer_runs = 200000
via_ir = true
use_literal_content = true
[profile.release.optimizer_details]
# # https://docs.soliditylang.org/en/v0.8.28/using-the-compiler.html#input-description
peephole = true                               # default true
jumpdestRemover = true                        # default true
simpleCounterForLoopUncheckedIncrement = true # default true
yul = true                                    # default true
# inliner = true                                # default false
# orderLiterals = true # default false
# deduplicate = true # default false
# cse = true # default false
# constantOptimizer = true # default false 

[profile.slither]
inherit = "default"
via_ir = true
