[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["node_modules", "lib"]
script = "scripts"
solc_version = "0.8.28"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@symbioticfi/=node_modules/@symbioticfi/",
    "forge-std/=lib/forge-std/src/",
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
]
[fmt]
bracket_spacing = true
int_types = "preserve"
sort_imports = true
single_line_statement_blocks = "preserve"
contract_new_lines = false

[profile.release]
gas_reports = ["*"]
gas_reports_ignore = [
    "MockERC20",
    "MockChainlink",
    "MockAaveDataProvider",
    "MockCollateral",
]
optimizer = true
optimizer_runs = 200000
via_ir = true
use_literal_content = true
[profile.release.optimizer_details]
# # https://docs.soliditylang.org/en/v0.8.28/using-the-compiler.html#input-description
peephole = true                               # default true
jumpdestRemover = true                        # default true
simpleCounterForLoopUncheckedIncrement = true # default true
yul = true                                    # default true
# inliner = true                                # default false
# orderLiterals = true # default false
# deduplicate = true # default false
# cse = true # default false
# constantOptimizer = true # default false 

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"

[etherscan]
mainnet = { key = "${MAINNET_API_KEY}" }
sepolia = { key = "${MAINNET_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
